# --------------tasks of Multi-Domain Information Handler----------------

personal_information_task:
  description: >
    Gather comprehensive personal details including full name, contact information,
    professional online profiles, and personal website. Ensure completeness and accuracy. Note that the user may not have all the information.
  expected_output: >
    Information of the user
    name: 
    phonenumber:
    email address:
    LinkedIn profile:
    other social media profiles:
    personal website link:

# education_task:
#   description: >
#     Compile all educational history including degrees obtained, institutions, graduation years,
#     GPA, honors, and relevant coursework.
#   expected_output: >
#     An organized summary of educational background detailing degrees, schools attended,
#     graduation dates, GPAs, and important courses.

# volunteer_work_task:
#   description: >
#     Document all volunteer experiences including roles, organizations, durations, and specific contributions.
#   expected_output: >
#     A comprehensive list of volunteer activities with descriptions of roles, durations, contributions, and achievements.

# awards_recognitions_task:
#   description: >
#     Gather all awards and recognitions received, detailing the nature of each award and the granting organization.
#   expected_output: >
#     A list of awards and recognitions with detailed descriptions of each, including the reasons and contexts for the awards.

# references_task:
#   description: >
#     Collect contact details and descriptions of relationships for all professional references.
#   expected_output: >
#     A list of professional references including full contact information and a brief description of the relationship with each.

# personal_traits_interests_task:
#   description: >
#     Identify personal qualities and hobbies that may be relevant to the job or company culture.
#   expected_output: >
#     A description of personal traits and interests that align with professional contexts and organizational culture.

# miscellaneous_task:
#   description: >
#     Collect any additional details relevant to the user's professional profile such as willingness to travel and availability for shifts.
#   expected_output: >
#     A list of miscellaneous details relevant to job applications, including travel willingness and shift availability.

# -------------Technical Details Agent (Technical Skills and Professional Affiliations Specialist) tasks--------------

# skills_task:
#   description: >
#     Identify and categorize all professional skills including technical, soft skills, and
#     proficiency levels. Include certifications and licenses.
#   expected_output: >
#     A detailed breakdown of skills organized by category such as programming, database management,
#     and soft skills with an indication of proficiency levels.

# professional_affiliations_task:
#   description: >
#     List all memberships in professional organizations including roles and responsibilities within these groups.
#   expected_output: >
#     A detailed account of professional affiliations, positions held, and the role played in each organization.

# ---------------Publications and Presentations Agent (Publications and Presentations Documenter)---------------

# publications_presentations_task:
#   description: >
#     Compile a list of all publications and presentations, detailing authors, titles, dates, and events where presented.
#   expected_output: >
#     A detailed list of publications and presentations, including co-authors, titles, publication dates, and event names.

# ------------------------ work_project_experience_agent ----------------

# work_experience_task:
#   description: >
#     Organize and document comprehensive work histories including job titles, durations, employers, responsibilities, and achievements. Highlight skills utilized and developed in each role to showcase professional growth and capabilities.
#   expected_output: >
#     A detailed and structured overview of work experience, presenting each role with clarity and emphasizing key contributions and skills.

# project_experience_task:
#   description: >
#     Compile and format detailed descriptions of projects including titles, technologies used, durations, roles, contributions, and outcomes. Ensure that each project is represented in a manner that highlights its significance and the user's role in achieving results.
#   expected_output: >
#     A comprehensive and organized presentation of project experiences, each described thoroughly with information on technologies, durations, roles, and achievements, along with links to repositories or live projects if applicable.

# ------------------------ career_planning_analyst_agent ----------------

# objective_summary_task:
#   description: >
#     Create a professional summary that highlights key qualifications, objectives, and aligns with the user's career goals.
#   expected_output: >
#     A concise professional summary that effectively communicates the user's strengths and career objectives.

# career_aspirations_task:
#   description: >
#     Analyze long-term career goals and suggest potential job titles based on detailed user attributes. Evaluate and align these aspirations with current job market opportunities.
#   expected_output: >
#     A strategic analysis of career aspirations, including suggested job titles and paths tailored to the user’s skills and goals.

# job_specific_requirements_task:
#   description: >
#     Assess and document specific job requirements such as availability, willingness to relocate, and salary expectations.
#   expected_output: >
#     A detailed list of job-specific requirements addressing the user's availability, relocation willingness, and expected salary, tailored to potential job applications.


# activities_leadership_task:
#   description: >
#     Document all leadership roles and activities, including specific achievements and impacts within these roles.
#   expected_output: >
#     An in-depth overview of leadership activities, detailing the roles, durations, responsibilities, and key achievements.

# languages_task:
#   description: >
#     Compile a detailed listing of all languages spoken by the user, along with proficiency levels for each.
#   expected_output: >
#     A comprehensive list of languages with an assessment of proficiency levels, enhancing the cultural and communication profile of the user.

# strengths_task:
#   description: >
#     Analyze and document the user's strengths based on feedback, self-assessment, and observed performance.
#   expected_output: >
#     A balanced view of the user's strengths, providing insights for potential employers and personal development.

# interests_task:
#   description: >
#     Identify and document detailed interests of the user that align with or enhance their professional profile.
#   expected_output: >
#     A detailed description of interests that complements the professional and personal traits, adding depth to the user's profile.

# developmental_activities_task:
#   description: >
#     Gather information on all developmental activities such as courses, training, workshops, conferences, seminars, webinars, bootcamps, hackathons, competitions, and scholarships.
#   expected_output: >
#     A comprehensive list and descriptions of developmental activities, showcasing ongoing learning and engagement in professional growth.




# _______________________________________________________________________________________________________________________

# projects_task:
#   description: >
#     Document comprehensive details about significant projects including titles, technologies used, durations, roles, contributions, and outcomes.
#   expected_output: >
#     An exhaustive description of projects with detailed accounts of titles, technologies, durations, roles played, contributions, and outcomes.



# career_aspirations_task:
#   description: >
#     Define long-term career goals and the types of roles and responsibilities the user is seeking in future positions.
#   expected_output: >
#     A detailed explanation of career aspirations, including specific roles and responsibilities the user aims to pursue.

# job_specific_requirements_task:
#   description: >
#     Identify any job-specific requirements such as availability, willingness to relocate, and salary expectations.
#   expected_output: >
#     A list of job-specific requirements tailored to the user's preferences and potential job descriptions.


# -----------------------------------------------------------


# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formated as markdown with out '```'