resume_compilation_task:
  description: >
    You will receive a structured JSON object containing organized resume data. Your task is to format this data into a professional resume in plain text format. 

    **Formatting Rules:**
    * **Strictly follow the format provided below, ensuring consistent spacing and use of new lines.** 
    * Place a single empty line between each section (e.g., Summary, Skills, Project Experience, Work Experience, Education, References).
    * Place a single empty line between each project or work experience entry.
    * Maintain consistent indentation. All bullet points should be indented with a single hyphen (-) followed by a space.
    * Avoid extra spaces between words or punctuation marks.
    * Ensure there is a single space before and after each "|" character.
    * Pay close attention to the specific formatting required for each section, such as the Education section. Make sure to include all required elements in the correct order.
    * In the Skills section, separate items with commas, not hyphens. Make sure to group skills under appropriate categories.

    Here is the structured JSON data you need to format:
    {resume_data_in_json} 

  expected_output: >
    Do not mention any section that is not present in the JSON data. For example, if the JSON data does not contain a "References" section or [[Personal Website URL]] do not include it in the resume output.

    [empty line]
    # **[User's First and Last Name]**
    [Phone] | [Email] | [LinkedIn/Profile URL] | [Personal Website URL] 
    [Address], [City], [State]

    [empty line]
    ## Summary
    [Summary]

    [empty line]
    ## Skills

    [empty line]
    **[Category 1]:** (eg, Programming Languages:)
    - [Skill 1], [Skill 2], [Skill 3], ... 

    [empty line]
    **[Category 2]:** (eg, Frameworks:)
    - [Skill 4], [Skill 5], ...

    [empty line]
    **[Category 3]:** (eg, Tools:)
    - [Skill 6], [Skill 7], ...

    [empty line]
    **Soft Skills:** 
    - [Skill 1], [Skill 2], [Skill 3], ...
    - [Skill 4], [Skill 5], ...

    [empty line]
    ## Project Experience
    ### [Project Title 1]
    [Start Month Year] - [End Month Year] ([Duration]) | [City], [State] 
    Technologies, frameworks, and tools used:  [List of technologies, separated by commas]
    Link: [Link to the project]
    - [Key achievement 1]
    - [Key achievement 2]
    - ...

    [empty line]
    ### [Project Title 2]
    [Start Month Year] - [End Month Year] ([Duration]) | [City], [State] 
    Technologies, frameworks, and tools used:  [List of technologies, separated by commas]
    Link: [Link to the project]
    - [Key achievement 1]
    - [Key achievement 2]
    - ...

    [empty line]
    ## Work Experience
    ### [Job Title 1]
    [Start Month Year] - [End Month Year] ([Duration]) | [Company Name] | [City], [State]
    Technologies, frameworks, and tools used:  [List of technologies, separated by commas]
    Link: [Link to the relevant work experience (e.g., company website)]
    - [Key achievement 1]
    - [Key achievement 2]
    - ...

    [empty line]
    ## Education
    **[University Name]**, [City], [State]
    - [Degree], [Major] | Graduated: [Graduation Date]
    - GPA: [GPA]

    [empty line]
    ## References

    ## [Other Sections you found in the JSON and you want to include in the resume]