# --------------tasks of Profile Building----------------

# list of tasks:
# - personal_information_extraction_task
# - education_extraction_task
# - volunteer_work_extraction_task
# - awards_recognitions_extraction_task
# - references_extraction_task
# - personal_traits_interests_extraction_task
# - miscellaneous_extraction_task
# - resume_build_task



personal_information_extraction_task:
  description: >
    You are given a tool that retrieves info simply by asking question as a list of strings. Use the tool to extract comprehensive personal details.

    How you should use the tool:
    argument:
    "question" : "Give me full name, phone number, email, LinkedIn, other social media profiles links, personal website link, portfolio link, GitHub profile, address, city, state, zip code, country."

    The tool will return a large chunk of information. look into the chunk to find your data. If you did not find a field, ask the tool again with the missing field.
    for example, if you didn't find the GitHub, ask the tool "GitHub" to get the GitHub link.

  expected_output: >
    User's Profile: 
    Full Name:
    Phone Number:
    Email:
    LinkedIn Profile:
    Other social media profiles links:
    Personal website link:
    Portfolio Link:
    GitHub Profile:
    Address:
    City:
    State:
    Zip Code:
    Country:

education_extraction_task:
  description: >
    You are given a tool that retrieves info simply by asking question as a list of strings. Use the tool to extract comprehensive education details.
    How you should use the tool:
    argument:
    "question" : "Give me the list of all educational qualifications, including degrees, majors, universities, graduation dates, and any honors or distinctions."
    The tool will return a large chunk of information. look into the chunk to find your data. If you did not find a field, Rerun the tool again with the missing field. 
  expected_output: >
    Education:
      Degree:
      Major:
      University:
      University Location:
      Graduation Date:
      Honors/Distinctions:

volunteer_work_extraction_task:
  description: >
    You are given a tool that retrieves info simply by asking question as a list of strings. Use the tool to extract comprehensive volunteer work details.
    How you should use the tool:
    argument:
    "question" : "Give me a list of all volunteer experiences, including organization names, roles, responsibilities, and dates."
    
    The tool will return a large chunk of information. look into the chunk to find your data. If you did not find a field, ask the tool again with the missing field. Do not make up any information.
  expected_output: >
    Volunteer Work:
      Organization Name:
      Role:
      Responsibilities:
      Dates:

awards_recognitions_extraction_task:
  description: >
    You are given a tool that retrieves info simply by asking question as a list of strings. Use the tool to extract comprehensive awards and recognitions details.
    How you should use the tool:
    argument:
    "question" : "Give me a list of all awards and recognitions, including award names, awarding organizations, dates, and reasons for recognition."
    
    The tool will return a large chunk of information. look into the chunk to find your data. If you did not find a field, ask the tool again with the missing field. Do not make up any information.
  expected_output: >
    Awards and Recognitions:
      Award Name:
      Awarding Organization:
      Date:
      Reason for Recognition:

references_extraction_task:
  description: >
    You are given a tool that retrieves info simply by asking question as a list of strings. Use the tool to extract comprehensive references details.
    How you should use the tool:
    argument:
    "question" : "Give me a list of all references, including names, positions, companies, contact information, and relationships to you."
    
    The tool will return a large chunk of information. look into the chunk to find your data. If you did not find a field, ask the tool again with the missing field. Do not make up any information.
  expected_output: >
    References:
      Name:
      Position:
      Company:
      Contact Information:
      Relationship:

personal_traits_interests_extraction_task:
  description: >
    You are given a tool that retrieves info simply by asking question as a list of strings. Use the tool to extract comprehensive personal traits and interests details.
    How you should use the tool:
    argument:
    "question" : "Give me a list of all personal traits and interests, including strengths, weaknesses, hobbies, and passions."
    
    The tool will return a large chunk of information. look into the chunk to find your data. If you did not find a field, ask the tool again with the missing field. Do not make up any information.
  expected_output: >
    Personal Traits and Interests:
      Strengths:
      Weaknesses:
      Hobbies:
      Passions:

miscellaneous_extraction_task:
  description: >
    You are given a tool that retrieves info simply by asking question as a list of strings. Use the tool to extract comprehensive miscellaneous details.
    How you should use the tool:
    argument:
    "question" : "Give me any additional information that you would like to include in your profile, such as languages spoken, certifications, professional affiliations, or other relevant details."
    
    The tool will return a large chunk of information. look into the chunk to find your data. If you did not find a field, ask the tool again with the missing field. Do not make up any information.
  expected_output: >
    Additional Information:
      Languages Spoken:
      Certifications:
      Professional Affiliations:
      Other Relevant Details:

resume_build_task:
  description: >
    You are given the context of all previous tasks of collecting necessary information to make a resume. Use all the knowledges to build a resume which closely aligns with the job description provided.

    If some information is missing, dont mention it in the resume. 
  expected_output: >
    A well-structured resume that includes all the necessary information gathered from the previous tasks. The resume should be tailored to the job description provided, highlighting the user's skills, experiences, and qualifications relevant to the position.
    
job_description_cross_check_task:
  description: >
    The task involves finding out the similarity between the Keyword and Phrase Extraction of a Job Post and the context received. You will get the "Keyword and Phrase Extraction" by using the tool. Use the context received from the previous tasks to find out the similarity between the Job's keywords and phrases and the context received.

  expected_output: >
    The expected output is a structured report that categorizes matches as 'Exact Match', 'Partial Match', or 'No Match'. Each category will include:
    - 'Exact Match': Direct correspondences between job description requirements and applicant's stated qualifications.
    - 'Partial Match': Related skills or experiences that do not directly match but are relevant to the job requirements.
    - 'No Match': Key areas where the applicant does not meet the job specifications.
    The report should also include a relevance score or percentage that quantifies the overall fit of the applicant to the job description, helping recruiters prioritize candidates efficiently.


# ------------------------ work_project_experience_agent ----------------

work_experience_extraction_task:
  description: >
    The task involves extracting detailed information about the user's work experience, including job titles, companies, durations, roles, responsibilities, and achievements. Use the tool to extract this information from the user's input.

    The tool will return a large chunk of information. Look into the chunk to find your data. You may need to ask the tool multiple times to extract all the expeiernces.

  expected_output: >
    Work Experience:
      Job Title:
      Company:
      Duration:
      Role:
      Responsibilities: (At least 3-4 responsibilities or more if possible)
        1.
        2.
        3.
        4.
        5.
        
      Achievements:



project_experience_extraction_task:
  description: >
    The task involves extracting detailed information about the user's project experiences, including project titles, durations, team sizes, roles, technologies used, and outcomes. Use the tool to extract this information from the user's input.

    The tool will return a large chunk of information. Look into the chunk to find your data. 
    
  expected_output: >
    Project Experience:
    Project name:
    Role:
    Description: 
    Key Highlights: 
      1.
      2.
      3.
      4.
      
    Technologies Used:
    Timeline:
    Team size:
    Outcomes:


# -------------Technical Details Agent (Technical Skills and Professional Affiliations Specialist) tasks--------------

# skills_extraction_task:
#   description: >
#     Your task is to comprehensively extract a list of skills and technologies from the user's projects and work experiences across various industries. You should utilize the tool to perform multiple queries, each tailored to specific categories such as technical skills, professional software, operational tools, and work methodologies.
    
#     Break down your queries to cover all areas thoroughly:
#     - Start by asking for technical skills used in projects and work experiences, which could include programming languages in tech, surgical techniques in healthcare, or teaching methods in education and so on.
#     - Next, inquire about professional software and tools that have been utilized, which could range from industry-specific tools like CAD software for engineers to CRM systems for sales professionals.
#     - Follow with questions on any operational tools or equipment used, which could include everything from heavy machinery in construction to laboratory equipment in science fields.
#     - Finally, ask about methodologies or strategic frameworks adopted in their professional practices, applicable across different sectors.

#     Compile the responses to these queries to form a complete inventory of skills and technologies. If any category appears incomplete or missing, rephrase your questions to fill these gaps. Ensure not to fabricate any information and rely solely on the data provided.

#   expected_output: >
#     The expected output should list all skills and technologies, categorized by type, derived directly from the user's input about their projects and work experiences across diverse industries:
#     - Technical Skills:
#       - Examples: Python, Java, Phlebotomy, Classroom Management
#     - Professional Software and Tools:
#       - Examples: AutoCAD, Salesforce, Adobe Suite, Microsoft Office
#     - Operational Tools:
#       - Examples: CNC machines, Stethoscopes, Paintbrushes
#     - Methodologies and Frameworks:
#       - Examples: Agile, Six Sigma, Montessori Method, Narrative Therapy

#     This comprehensive listing will assist in accurately assessing the candidate’s versatility and suitability for various roles across multiple sectors.



# skills_extraction_task:
#   description: >
#     You will begin by using the "Search for the chunk of relevant content" tool to extract a comprehensive list of skills and technologies from the candidate's submissions. Following this extraction, you will use the fileReaderTool to retrieve a list of keywords that are critical to the job description. Your task is to cross-check and identify which of the extracted skills exactly match or partially match the keywords from the job description. If a skill is not listed in the job description but you deem it somewhat relevant, include it in your final list. Your final output should very brief. 
#   expected_output: >
#     The expected output is a detailed list of skills categorized into three types:
#     - Exact Match: Skills that directly correspond with those listed in the job description.
#     - Partial Match: Skills that, while not explicitly listed, are closely related to or valuable for the job role.
#     - Relevant Skills: Skills not listed but considered valuable for the role, each accompanied by a justification for its inclusion.
#     This categorized list of skills will later be utilized to craft tailored resumes that highlight the candidate’s most relevant qualifications.



# professional_affiliations_task:
#   description: >
#     List all memberships in professional organizations including roles and responsibilities within these groups.
#   expected_output: >
#     A detailed account of professional affiliations, positions held, and the role played in each organization.

# ---------------Publications and Presentations Agent (Publications and Presentations Documenter)---------------

# publications_presentations_task:
#   description: >
#     Compile a list of all publications and presentations, detailing authors, titles, dates, and events where presented.
#   expected_output: >
#     A detailed list of publications and presentations, including co-authors, titles, publication dates, and event names.



# ------------------------ career_planning_analyst_agent ----------------

# objective_summary_task:
#   description: >
#     Create a professional summary that highlights key qualifications, objectives, and aligns with the user's career goals.
#   expected_output: >
#     A concise professional summary that effectively communicates the user's strengths and career objectives.

# career_aspirations_task:
#   description: >
#     Analyze long-term career goals and suggest potential job titles based on detailed user attributes. Evaluate and align these aspirations with current job market opportunities.
#   expected_output: >
#     A strategic analysis of career aspirations, including suggested job titles and paths tailored to the user’s skills and goals.

# job_specific_requirements_task:
#   description: >
#     Assess and document specific job requirements such as availability, willingness to relocate, and salary expectations.
#   expected_output: >
#     A detailed list of job-specific requirements addressing the user's availability, relocation willingness, and expected salary, tailored to potential job applications.


# activities_leadership_task:
#   description: >
#     Document all leadership roles and activities, including specific achievements and impacts within these roles.
#   expected_output: >
#     An in-depth overview of leadership activities, detailing the roles, durations, responsibilities, and key achievements.

# languages_task:
#   description: >
#     Compile a detailed listing of all languages spoken by the user, along with proficiency levels for each.
#   expected_output: >
#     A comprehensive list of languages with an assessment of proficiency levels, enhancing the cultural and communication profile of the user.

# strengths_task:
#   description: >
#     Analyze and document the user's strengths based on feedback, self-assessment, and observed performance.
#   expected_output: >
#     A balanced view of the user's strengths, providing insights for potential employers and personal development.

# interests_task:
#   description: >
#     Identify and document detailed interests of the user that align with or enhance their professional profile.
#   expected_output: >
#     A detailed description of interests that complements the professional and personal traits, adding depth to the user's profile.

# developmental_activities_task:
#   description: >
#     Gather information on all developmental activities such as courses, training, workshops, conferences, seminars, webinars, bootcamps, hackathons, competitions, and scholarships.
#   expected_output: >
#     A comprehensive list and descriptions of developmental activities, showcasing ongoing learning and engagement in professional growth.




# _______________________________________________________________________________________________________________________

# projects_task:
#   description: >
#     Document comprehensive details about significant projects including titles, technologies used, durations, roles, contributions, and outcomes.
#   expected_output: >
#     An exhaustive description of projects with detailed accounts of titles, technologies, durations, roles played, contributions, and outcomes.

# career_aspirations_task:
#   description: >
#     Define long-term career goals and the types of roles and responsibilities the user is seeking in future positions.
#   expected_output: >
#     A detailed explanation of career aspirations, including specific roles and responsibilities the user aims to pursue.

# job_specific_requirements_task:
#   description: >
#     Identify any job-specific requirements such as availability, willingness to relocate, and salary expectations.
#   expected_output: >
#     A list of job-specific requirements tailored to the user's preferences and potential job descriptions.


